SOURCES += \
    $$PWD/songersort/SongerSort.cpp \
    $$PWD/rankinglist/RankingList.cpp \
    $$PWD/songlistsort/SonglistSort.cpp \
    $$PWD/radiohost/RadioHost.cpp \
    $$PWD/musicscene/MusicScene.cpp \
    $$PWD/vipmember/VipMember.cpp \
    $$PWD/HomeWidget.cpp \
    $$PWD/SelectButtons.cpp \
    $$PWD/recommend/CentralHomeForm.cpp \
    $$PWD/recommend/GalleryItemForm.cpp \
    $$PWD/recommend/PicWallItem.cpp \
    $$PWD/recommend/RecommendForm.cpp \
    $$PWD/recommend/SearchForm.cpp \
    $$PWD/recommend/Slideshow.cpp \
    $$PWD/recommend/StackItem.cpp \
    $$PWD/recommend/StackItemForm.cpp \
    $$PWD/songersort/SongItem.cpp \
    $$PWD/songlistsort/TagsItem.cpp \
    $$PWD/songlistsort/TagsMenu.cpp \
    $$PWD/songlistsort/TagsMenuItem.cpp \
    $$PWD/CusLabelItem.cpp \
    $$PWD/HoverMask.cpp \
    $$PWD/vipmember/HotDownload.cpp \
    $$PWD/vipmember/HotDownloadItem.cpp \
    $$PWD/vipmember/HotSort.cpp \
    $$PWD/TrianButton.cpp \
    $$PWD/vipmember/HotVideoItem.cpp \
    $$PWD/vipmember/HotVideo.cpp \
    $$PWD/rankinglist/RankItem.cpp \
    $$PWD/rankinglist/RankListItem.cpp \
    $$PWD/videosmv/MainVideoMv.cpp \
    $$PWD/videosmv/MultipType.cpp \
    $$PWD/videosmv/MVRecmmend.cpp \
    $$PWD/videosmv/MVSortType.cpp \
    $$PWD/videosmv/RecmmendVideoItem.cpp \
    $$PWD/videosmv/VideoItem.cpp \
    $$PWD/videomember/CusStackWidget.cpp \
    $$PWD/videomember/MainMembForm.cpp \
    $$PWD/videomember/MemberVideoItem.cpp \
    $$PWD/videomember/MemberVipOpen.cpp \
    $$PWD/videomember/SwitchVideoType.cpp \
    $$PWD/videomember/VideoSortType.cpp \
    $$PWD/videomember/CusPusgButton.cpp \
    $$PWD/VideoItem.cpp

HEADERS += \
    $$PWD/songersort/SongerSort.h \
    $$PWD/rankinglist/RankingList.h \
    $$PWD/songlistsort/SonglistSort.h \
    $$PWD/radiohost/RadioHost.h \
    $$PWD/musicscene/MusicScene.h \
    $$PWD/vipmember/VipMember.h \
    $$PWD/HomeWidget.h \
    $$PWD/SelectButtons.h \
    $$PWD/recommend/CentralHomeForm.h \
    $$PWD/recommend/GalleryItemForm.h \
    $$PWD/recommend/PicWallItem.h \
    $$PWD/recommend/RecommendForm.h \
    $$PWD/recommend/SearchForm.h \
    $$PWD/recommend/Slideshow.h \
    $$PWD/recommend/StackItem.h \
    $$PWD/recommend/StackItemForm.h \
    $$PWD/songersort/SongItem.h \
    $$PWD/songlistsort/TagsItem.h \
    $$PWD/songlistsort/TagsMenu.h \
    $$PWD/songlistsort/TagsMenuItem.h \
    $$PWD/CusLabelItem.h \
    $$PWD/HoverMask.h \
    $$PWD/vipmember/HotDownload.h \
    $$PWD/vipmember/HotDownloadItem.h \
    $$PWD/vipmember/HotSort.h \
    $$PWD/TrianButton.h \
    $$PWD/vipmember/HotVideoItem.h \
    $$PWD/vipmember/HotVideo.h \
    $$PWD/rankinglist/RankItem.h \
    $$PWD/rankinglist/RankListItem.h \
    $$PWD/videosmv/MainVideoMv.h \
    $$PWD/videosmv/MultipType.h \
    $$PWD/videosmv/MVRecmmend.h \
    $$PWD/videosmv/MVSortType.h \
    $$PWD/videosmv/RecmmendVideoItem.h \
    $$PWD/videosmv/VideoItem.h \
    $$PWD/videomember/CusStackWidget.h \
    $$PWD/videomember/MainMembForm.h \
    $$PWD/videomember/MemberVideoItem.h \
    $$PWD/videomember/MemberVipOpen.h \
    $$PWD/videomember/SwitchVideoType.h \
    $$PWD/videomember/VideoSortType.h \
    $$PWD/videomember/CusPusgButton.h \
    $$PWD/VideoItem.h

FORMS += \
    $$PWD/songersort/SongerSort.ui \
    $$PWD/rankinglist/RankingList.ui \
    $$PWD/songlistsort/SonglistSort.ui \
    $$PWD/radiohost/RadioHost.ui \
    $$PWD/musicscene/MusicScene.ui \
    $$PWD/vipmember/VipMember.ui \
    $$PWD/HomeWidget.ui \
    $$PWD/SelectButtons.ui \
    $$PWD/recommend/GalleryItemForm.ui \
    $$PWD/recommend/PicWallItem.ui \
    $$PWD/recommend/RecommendForm.ui \
    $$PWD/recommend/SearchForm.ui \
    $$PWD/recommend/Slideshow.ui \
    $$PWD/recommend/StackItem.ui \
    $$PWD/recommend/StackItemForm.ui \
    $$PWD/songersort/SongItem.ui \
    $$PWD/songlistsort/TagsItem.ui \
    $$PWD/songlistsort/TagsMenu.ui \
    $$PWD/songlistsort/TagsMenuItem.ui \
    $$PWD/CusLabelItem.ui \
    $$PWD/vipmember/HotDownload.ui \
    $$PWD/vipmember/HotDownloadItem.ui \
    $$PWD/vipmember/HotSort.ui \
    $$PWD/TrianButton.ui \
    $$PWD/vipmember/HotVideoItem.ui \
    $$PWD/vipmember/HotVideo.ui \
    $$PWD/rankinglist/RankItem.ui \
    $$PWD/rankinglist/RankListItem.ui \
    $$PWD/videosmv/MainVideoMv.ui \
    $$PWD/videosmv/MultipType.ui \
    $$PWD/videosmv/MVRecmmend.ui \
    $$PWD/videosmv/MVSortType.ui \
    $$PWD/videosmv/RecmmendVideoItem.ui \
    $$PWD/videosmv/VideoItem.ui \
    $$PWD/videomember/MainMembForm.ui \
    $$PWD/videomember/MemberVideoItem.ui \
    $$PWD/videomember/MemberVipOpen.ui \
    $$PWD/videomember/SwitchVideoType.ui \
    $$PWD/videomember/VideoSortType.ui \
    $$PWD/VideoItem.ui

